In [1]:
import torch

In [16]:
from mmdet.models import MobileNetV2, SSDVGG

model = MobileNetV2(out_indices=(0,1,2,3,4,5,6,7))
ip=torch.rand(1,3,320,320)
outputs = model(ip)

for output in outputs:
    print(output.shape)
print("-------")
model = SSDVGG(depth=16,
        with_last_pool=False,
        ceil_mode=True,
        out_feature_indices=(0,1,2,3,4,5,6,7,8,22,34,35,36,37),)
ip=torch.rand(1,3,320,320)
outputs = model(ip)

for output in outputs:
    print(output.shape)


torch.Size([1, 16, 160, 160])
torch.Size([1, 24, 80, 80])
torch.Size([1, 32, 40, 40])
torch.Size([1, 64, 20, 20])
torch.Size([1, 96, 20, 20])
torch.Size([1, 160, 10, 10])
torch.Size([1, 320, 10, 10])
torch.Size([1, 1280, 10, 10])
-------
torch.Size([1, 64, 320, 320])
torch.Size([1, 64, 320, 320])
torch.Size([1, 64, 320, 320])
torch.Size([1, 64, 320, 320])
torch.Size([1, 64, 160, 160])
torch.Size([1, 128, 160, 160])
torch.Size([1, 128, 160, 160])
torch.Size([1, 128, 160, 160])
torch.Size([1, 128, 160, 160])
torch.Size([1, 512, 40, 40])
torch.Size([1, 1024, 20, 20])


In [17]:
torch.max(torch.rand(1,2,3,4))

tensor(0.9645)

In [32]:
mask3d = torch.round(torch.rand(8,4,4))
print(mask3d[0])
mask5d_ = mask3d.unsqueeze(1).unsqueeze(1)
print(mask5d_.shape)
mask5d_ = mask5d_.expand_as(torch.rand(8,5,6,4,4))
print(mask5d_.shape)
print(mask5d_[0,3,1])

tensor([[[0.5871, 0.0195, 0.0523],
         [0.6187, 0.6512, 0.0450],
         [0.5562, 0.7524, 0.6208]],

        [[0.7530, 0.8364, 0.1076],
         [0.3092, 0.3029, 0.0502],
         [0.1880, 0.9624, 0.0229]]])
tensor([[[ True, False, False],
         [ True,  True, False],
         [ True,  True,  True]],

        [[ True,  True, False],
         [False, False, False],
         [False,  True, False]]])
tensor([[ True,  True, False],
        [ True,  True, False],
        [ True,  True,  True]])
tensor([[[ True,  True, False],
         [ True,  True, False],
         [ True,  True,  True]],

        [[ True,  True, False],
         [ True,  True, False],
         [ True,  True,  True]]])


In [34]:
from kornia.losses import ssim_loss

In [49]:
a = torch.rand(1,1,5,5)
b = torch.rand(1,1,5,5)
b = a
print(a), print(b)
ssim_loss(a,b, 3)

tensor([[[[0.5132, 0.8639, 0.8062, 0.9390, 0.5233],
          [0.4605, 0.1419, 0.4152, 0.5898, 0.6816],
          [0.7861, 0.0202, 0.7319, 0.0143, 0.8278],
          [0.3948, 0.0838, 0.1135, 0.4422, 0.7564],
          [0.9253, 0.6317, 0.6051, 0.4274, 0.1532]]]])
tensor([[[[0.5132, 0.8639, 0.8062, 0.9390, 0.5233],
          [0.4605, 0.1419, 0.4152, 0.5898, 0.6816],
          [0.7861, 0.0202, 0.7319, 0.0143, 0.8278],
          [0.3948, 0.0838, 0.1135, 0.4422, 0.7564],
          [0.9253, 0.6317, 0.6051, 0.4274, 0.1532]]]])


tensor(0.)